'use client';

import { BylawsClient } from '@/components/bylaws-client';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/context/language-context';
import { Download } from 'lucide-react';
import { useEffect, useMemo } from 'react';
import { useDoc, useFirestore, useMemoFirebase } from '@/firebase';
import { doc } from 'firebase/firestore';
import { Skeleton } from '@/components/ui/skeleton';

const staticTranslations = {
  en: {
    title: 'Bylaws',
    description: 'Review the official bylaws of the Grand Coptic Benevolent Society or use our AI tool to summarize the document.',
    pageTitle: 'Society Bylaws',
    pageSubtitle: 'Our operations are guided by a comprehensive set of bylaws. You can download the full official document or use our AI tool for a quick summary.',
    officialDocument: 'Official Document',
    downloadButton: 'Download Full Bylaws (PDF)',
    // Translations for BylawsClient
    cardTitle: 'AI-Powered Bylaws Summarizer',
    cardDescription: 'Have a long legal document? Upload the PDF to get a concise, easy-to-understand summary generated by AI.',
    uploadLabel: 'Upload PDF Document',
    summarizing: 'Summarizing...',
    summarize: 'Summarize',
    errorTitle: 'Error',
    summaryTitle: 'Generated Summary',
  },
  ar: {
    title: 'النظام الأساسي',
    description: 'راجع النظام الأساسي الرسمي للجمعية القبطية الخيرية الكبرى أو استخدم أداة الذكاء الاصطناعي الخاصة بنا لتلخيص المستند.',
    pageTitle: 'النظام الأساسي للجمعية',
    pageSubtitle: 'تسترشد عملياتنا بمجموعة شاملة من اللوائح. يمكنك تنزيل المستند الرسمي الكامل أو استخدام أداة الذكاء الاصطناعي الخاصة بنا للحصول على ملخص سريع.',
    officialDocument: 'المستند الرسمي',
    downloadButton: 'تنزيل النظام الأساسي الكامل (PDF)',
    // Translations for BylawsClient
    cardTitle: 'ملخص النظام الأساسي المدعوم بالذكاء الاصطناعي',
    cardDescription: 'هل لديك مستند قانوني طويل؟ قم بتحميل ملف PDF للحصول على ملخص موجز وسهل الفهم تم إنشاؤه بواسطة الذكاء الاصطناعي.',
    uploadLabel: 'تحميل مستند PDF',
    summarizing: 'جارٍ التلخيص...',
    summarize: 'تلخيص',
    errorTitle: 'خطأ',
    summaryTitle: 'الملخص الذي تم إنشاؤه',
  }
};

export default function BylawsPage() {
  const { language, direction } = useLanguage();

  const firestore = useFirestore();
  const contentRef = useMemoFirebase(() => firestore ? doc(firestore, 'page_content', 'bylaws') : null, [firestore]);
  const { data: dynamicContent, isLoading } = useDoc(contentRef);

  const t = useMemo(() => {
    const content = dynamicContent ? (language === 'ar' ? dynamicContent.contentAr : dynamicContent.contentEn) : null;
    return content || staticTranslations[language];
  }, [dynamicContent, language]);

  useEffect(() => {
    const pageTitle = t.title || staticTranslations[language].title;
    document.title = `${pageTitle} | ${language === 'en' ? 'Grand Coptic Benevolent Society' : 'الجمعية القبطية الخيرية الكبرى'}`;
  }, [t, language]);

  return (
    <div className="bg-background" dir={direction}>
      <div className="container px-4 sm:px-6 lg:px-8 py-16 lg:py-24 space-y-16">
        <div className="text-center">
            {isLoading ? (
                <>
                    <Skeleton className="h-12 w-3/4 mx-auto" />
                    <Skeleton className="h-6 w-full max-w-3xl mx-auto mt-4" />
                </>
            ) : (
                <>
                    <h1 className="font-headline text-4xl md:text-5xl text-primary">{t.pageTitle}</h1>
                    <p className="mt-4 max-w-3xl mx-auto text-lg text-muted-foreground">
                        {t.pageSubtitle}
                    </p>
                </>
            )}
        </div>

        <div className="flex flex-col items-center gap-4">
            {isLoading ? <Skeleton className="h-8 w-48" /> : <h2 className="font-headline text-2xl text-primary">{t.officialDocument}</h2>}
            <Button size="lg" asChild>
                {/* The actual bylaws.pdf should be placed in the /public directory */}
                <a href="/bylaws.pdf" download>
                    <Download className="mr-2 h-5 w-5 rtl:ml-2 rtl:mr-0" />
                    {isLoading ? <Skeleton className="h-6 w-56" /> : t.downloadButton}
                </a>
            </Button>
        </div>
        
        <BylawsClient translations={t} />
      </div>
    </div>
  );
}
