'use client';

import { useState } from 'react';
import { summarizeBylaws } from '@/ai/flows/bylaws-summarization';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, FileUp, FileText, AlertCircle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

export function BylawsClient() {
  const [file, setFile] = useState<File | null>(null);
  const [summary, setSummary] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');
  const { toast } = useToast();

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (selectedFile) {
      if (selectedFile.type !== 'application/pdf') {
        toast({
          variant: 'destructive',
          title: 'Invalid File Type',
          description: 'Please upload a PDF file.',
        });
        setFile(null);
        event.target.value = ''; // Reset file input
        return;
      }
      setFile(selectedFile);
      setSummary('');
      setError('');
    }
  };

  const handleSummarize = async () => {
    if (!file) {
      toast({
        variant: 'destructive',
        title: 'No File Selected',
        description: 'Please choose a PDF file to summarize.',
      });
      return;
    }

    setIsLoading(true);
    setError('');
    setSummary('');

    try {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = async () => {
        const pdfDataUri = reader.result as string;
        const result = await summarizeBylaws({ pdfDataUri });
        setSummary(result.summary);
      };
      reader.onerror = (error) => {
        console.error('Error reading file:', error);
        setError('Failed to read the selected file. Please try again.');
      };
    } catch (e) {
      console.error(e);
      const errorMessage = e instanceof Error ? e.message : 'An unknown error occurred.';
      setError(`Failed to generate summary. ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="max-w-4xl mx-auto">
      <CardHeader>
        <CardTitle className="font-headline text-2xl text-primary">AI-Powered Bylaws Summarizer</CardTitle>
        <CardDescription>
          Have a long legal document? Upload the PDF to get a concise, easy-to-understand summary generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="bylaws-upload">Upload PDF Document</Label>
          <div className="flex items-center gap-4">
            <Input id="bylaws-upload" type="file" accept="application/pdf" onChange={handleFileChange} className="flex-grow" />
            <Button onClick={handleSummarize} disabled={isLoading || !file}>
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Summarizing...
                </>
              ) : (
                <>
                  <FileUp className="mr-2 h-4 w-4" />
                  Summarize
                </>
              )}
            </Button>
          </div>
        </div>

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {summary && (
          <div className="space-y-4 rounded-lg border bg-secondary/50 p-4">
            <h3 className="font-headline text-xl text-primary flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Generated Summary
            </h3>
            <div className="prose prose-sm max-w-none text-foreground whitespace-pre-wrap">{summary}</div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
